### PR TITLE
Add a std ping pong benchmark for comparison

### PR DESCRIPTION
**Pull request by teburd**
Adds a simple std::sync::mpsc::channel benchmark to easily see how much faster this is.

The answer is _much_ faster.

### CODE REVIEW

**Comment by ujh** [comment]
Yeah, unfortunately it is and I had to switch back to using them. But it should be possible to use the mpsc channels and an extra thread to produce an mpmc channel.

**Comment by johnshaw** [comment]
@bfrog All these queues should be near optimal in terms of core-to-core latency. There seems to be some Rust/llvm overhead that make this a bit slower than an equivalent C/C++ version which I haven't investigated much (times are good enough). The latency is primarily bounded by the cache coherency implementation and is highly dependent on which cores the producers and consumers are running. For example, bouncing off L1 between two hyper threads is going to be significantly faster than traversing QPI between two cpus. The multi producer/consumer versions require a locked bus operation which are fairly expensive so I tend to avoid these if possible. I usually prefer using multiple spsc queues to avoid the atomic instruction overhead. There are higher bandwidth ways to push data over the memory bus, but this tends to be sufficient for pointer-sized data, which is the common use case.

@ujh Yea, I suspect the use case for these is fairly limited. Especially since it requires polling to realize the latency win. If you're serious about latency then this isn't an issue. On the other hand, these could integrate into a dispatch loop along with a kernel signaling mechanism, such as eventfd.

**Comment by ujh** [comment]
My use case is a control thread and N workers. I use one mpsc channel to send the results from the workers to the controller. The response also contains a `Sender` so that the controller can send the next chunk of work. Switching to magnetic made this 3x slower. But then I also tried to use a spmc channel to send the work to the threads so it's not a 1:1 comparison anymore.

**Comment by johnshaw** [comment]
I'm not familiar with the details of your architecture, so I can't say for certain why you would see a 3x performance hit. It's possible there is an issue with the queue, but I suspect it's just a square peg round hole problem. If N+1 > num cores, then you might have thread contention issues since the blocking push/pop busy-wait instead of yielding like the standard mpsc queue.

**Comment by ujh** [comment]
Yes that could be it. I have N workers (where N is the number of cores) and one thread of the controller. I will try again soon and actually profile it.

**Pull request merged**
